dist: trusty
sudo: required
language: python

services:
- docker

python:
- 3.6

before_install:
- git clone https://github.com/boutiques/boutiques.git
- docker build -t boutiques/example1:test ./boutiques/tools/python/boutiques/schema/examples/example1
- rm boutiques -Rf
- cd ${TRAVIS_BUILD_DIR}

install:
- python ./pipeline-tester/setup.py install

script:
- cd pipeline-tester/atop
- python manage.py test atop
