# Generated by Django 2.0.3 on 2018-04-03 04:33

import atop.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100, verbose_name='tool name')),
                ('execution_status', models.IntegerField(default=0, verbose_name='status')),
                ('is_public', models.BooleanField(default=False, verbose_name='exposure')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='date added')),
                ('data_url', models.URLField(default='')),
                ('data_file', models.FileField(default='', upload_to=atop.models.user_directory_path)),
                ('automatic_updating', models.BooleanField(default=False, verbose_name='updated automatically')),
                ('error_message', models.TextField(default='')),
                ('md5', models.CharField(max_length=16)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_status', models.IntegerField(default=0, verbose_name='status')),
                ('test_name', models.CharField(max_length=100, verbose_name='test name')),
                ('evaluated_invocation', models.CharField(max_length=500, verbose_name='invocation')),
                ('code', models.TextField()),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atop.Descriptor')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptorTestAssertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('operand1', models.CharField(max_length=100)),
                ('operand2', models.CharField(max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atop.Descriptor')),
            ],
        ),
    ]
