# Generated by Django 2.0.3 on 2018-04-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptortestassertion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atop.DescriptorTest'),
        ),
    ]
